const firebaseErrorMessages = {
    "auth/invalid-email": "Invalid email address.",
    "auth/user-disabled": "User account disabled.",
    "auth/user-not-found": "User not found.",
    "auth/wrong-password": "Incorrect password.",
    "auth/email-already-in-use": "Email already in use.",
    "auth/weak-password": "Weak password.",
    "auth/operation-not-allowed": "Operation not allowed.",
    "auth/invalid-verification-code": "Invalid verification code.",
    "auth/invalid-verification-id": "Invalid verification ID.",
    "auth/missing-verification-code": "Missing verification code.",
    "auth/missing-verification-id": "Missing verification ID.",
    "auth/credential-already-in-use": "Credential already in use.",
    "auth/invalid-credential": "Invalid credential.",
    "auth/account-exists-with-different-credential": "Account exists with different credential.",
    "auth/invalid-api-key": "Invalid API key.",
    "auth/network-request-failed": "Network error.",
    "auth/too-many-requests": "Too many requests. Try again later.",
    "auth/popup-blocked": "Popup blocked by browser.",
    "auth/popup-closed-by-user": "Popup closed by user.",
    "auth/requires-recent-login": "Recent login required.",
    "auth/user-token-expired": "User credential expired.",
    "auth/web-storage-unsupported": "Web storage unsupported.",
    "auth/invalid-custom-token": "Invalid custom token.",
    "auth/custom-token-mismatch": "Custom token mismatch.",
    "auth/invalid-message-payload": "Invalid email template.",
    "auth/invalid-recipient-email": "Invalid recipient email.",
    "auth/invalid-sender": "Invalid sender email.",
    "auth/invalid-verification-link": "Invalid verification link."
};

export default firebaseErrorMessages